export const API = 'API';
export const WHEEL_OF_FATE_SUCCESS = 'WHEEL_OF_FATE_SUCCESS';
export const WHEEL_OF_FATE_ERROR = 'WHEEL_OF_FATE_ERROR';
export const SHIFTS_HISTORY_SUCCESS = 'SHIFTS_HISTORY_SUCCESS';
export const SHIFTS_HISTORY_ERROR = 'SHIFTS_HISTORY_ERROR';
export const GET_ENGINEERS_SUCCESS = 'GET_ENGINEERS_SUCCESS';
